import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AOS from 'aos';
import { useEffect } from "react";
import Head from 'next/head';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nihal's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
          <title>Default title</title>
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
